user_feedback/urls.py
from django.conf.urls import url

from . import views


app_name = "user_feedback"


def flow_patterns():
    return [url(r"^post", views.post_feedback_json, name="post")]


urlpatterns = sum([flow_patterns()], [])

user_feedback/models.py
from django.contrib.auth import get_user_model
from django.db import models

User = get_user_model()


class Feedback(models.Model):

    ONE_TO_FIVE_RATING_CHOICES = ((1, "1"), (2, "2"), (3, "3"), (4, "4"), (5, "5"))
    FEEDBACK_TYPE = ((1, "Bug Report"), (2, "Feature Request"), (3, "Review"))
    type = models.PositiveIntegerField(choices=FEEDBACK_TYPE)
    rating = models.PositiveIntegerField(choices=ONE_TO_FIVE_RATING_CHOICES, null=True)
    text = models.TextField(max_length=400, null=True, blank=True)
    url = models.CharField(max_length=50)
    author = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    created_on = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.text

    class Meta:
        verbose_name = "Feedback"
        verbose_name_plural = "Feedback"

user_feedback/views.py
from datetime import datetime, timezone, timedelta
import bleach
import json

from django.contrib.auth.decorators import login_required
from django.core.mail import mail_admins
from django.http import JsonResponse
from django.views.decorators.http import require_POST

from .models import Feedback
from .serializers import FeedbackSerializer


@require_POST
@login_required
def post_feedback_json(request):
    data = json.loads(request.POST.get("json"))
    data["text"] = bleach.clean(data["text"], tags=[], strip=True).rstrip()
    data["author"] = request.user.pk
    serializer = FeedbackSerializer(data=data)
    if serializer.is_valid():
        feedback_object = serializer.save()
        if feedback_object.type == 1:
            send_bug_report_emails(request, data)
        return JsonResponse({"action": "posted"})
    else:
        return JsonResponse({"action": "error"})


def send_bug_report_emails(request, data):
    mail_admins(
        subject="URGENT - bug report",
        message="A bug has been reported on %s's %s. The user has written the "
        "following: '%s' There have been %d other bugs reported in the "
        "last 10 days at this url."
        % (
            request.get_host(),
            data["url"][1:-1],
            data["text"],
            Feedback.objects.filter(
                type=1,
                url=data["url"],
                created_on__lte=datetime.now(timezone.utc),
                created_on__gt=datetime.now(timezone.utc) - timedelta(days=10),
            ).count()
            - 1,
        ),
        fail_silently=False,
    )

user_feedback/templates/user_feedback/template.html
{% load static i18n %} {% get_current_language as LANGUAGE_CODE %}
<!DOCTYPE html>
<html lang="{{LANGUAGE_CODE}}">
  <head>
    <link
      href="https://fonts.googleapis.com/css?family=Material+Icons|Roboto|Fanwood+Text:400i|Quicksand:300,400|Rubik:200,300,300i,400"
      rel="stylesheet"
      type="text/css"
    />
    <!-- ** jquery -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <!-- ** user_feedback scripts -->
    <script
      src="{% static 'user_feedback/js/scripts.min.js' %}"
      defer="true"
    ></script>

    <link
      rel="stylesheet"
      href="{% static 'course_flow/css/preact_styles.css' %}"
    />
  </head>
  <body>
    <div id="user-feedback-container">
      {% csrf_token %}
    </div>
  </body>
  <script>
    window.addEventListener("load", function() {
      root.injectDialog(
        "{% trans 'Let us know how we can improve your experience!' %}",
        "{% static 'user_feedback/example_logo/aperture.svg' %}",
        "{% trans 'Thanks for your feedback!' %}",
        "{% trans 'Sorry, please try again later!' %}",
        "{% url 'user_feedback:post' %}"
      );
    });
  </script>
</html>